### ISSUE TITLE
LOD Data Resolutions above 256 don't work on iGPUs on Mac

### ISSUE THREAD

**Issue by moosichu** [wave-harmonic/crest#384]
**Describe the bug**
Here is everything with a LOD Data Resolution of 256
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/10348641/71516481-8853d180-28a9-11ea-8a14-37795b9bb156.png">

Things go wrong for any value above that (using 384 here as it is the default, but have checked 260 and 512 amongs other values, have checked that values below 256 do seem to work).

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/10348641/71516540-c9e47c80-28a9-11ea-98dd-b1b386c11f3f.png">

According to @daleeidd in issue [#279](https://github.com/crest-ocean/crest/issues/279#issuecomment-566423133), this *only* affects integrated GPUs and not discrete GPUs. I cannot I can only confirm that I get the issue on my MacBook Air as well.

**Log**
Nothing is in the log!

**Versions**
Which render pipeline (built-in/LWRP/HDRP)? Which version of LWRP/HDRP? Which version of unity (including minor, i.e. 2019.1.0f2)? 

**Platform**
 - Editor
 - MacOS Catalina (Metal)

**Hardware**
Confirmed Cases:
- Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
- 1.6 GHz Dual-Core Intel Core i5 (Intel UHD Graphics 617 1536 MB)

**Additional context**
Very easy to reproduce, but no error messages or other feedback that could indicate the possible cause of the error.

**Comment by daleeidd** [comment]
Thanks! I have some more information.

Some more information for the machine I already reported:
Mac Mini 2018 **(affected)**
MacOS Catalina 10.15.2 (Metal)
Intel UHD Graphics 630 (1536 MB)
Metal: Supported, feature set macOS GPUFamily2 v1

Another machine I was able to test where LOD 384 works:
MacBook Pro 2014 **(unaffected)**
MacOS Catalina 10.15.2 (Metal)
Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
Intel Iris Pro (1536 MB)
Metal: Supported, feature set macOS GPUFamily1 v4
16 GB 1600 MHz DDR3

It could be the Metal version?

**Comment by moosichu** [comment]
Thanks for the update! For the record, what I've seen:

MacBook Air (Retina, 13-inch, 2019) **(affected)**:
MacOS Catalina 10.15.1 (19B88) (Metal)
1.6 GHz Dual-Core Intel Core i5
Intel UHD Graphics 617 1536 MB
8 GB 2133 MHz LPDDR3

**Comment by huwb** [comment]
I never replied to this. Thanks for logging it! What are the next steps?

Some ideas..

What is failing exactly, do we know? I pushed a branch `fix/mac-freezes-pretend-workload` which does a bunch of random clears - does this work with resolution > 256? It should make crazy colours in one of the anim waves lods/jittery ocean when enabled (through the debug gui).

Does it fail also in standalone builds? Is there anything in the standalone build log?

**Comment by moosichu** [comment]
I will spend this weekend looking at Mac issues, so will get back to you on these ones!

**Comment by daleeidd** [comment]
I edited the original post as it only affects the Editor.

![No Issue](https://user-images.githubusercontent.com/5249806/77861187-2b2c3b00-725f-11ea-968f-b3e568cfce1d.jpg)
256

![Issue Low](https://user-images.githubusercontent.com/5249806/77861146-0041e700-725f-11ea-9e61-35415e4a1f66.jpg)
384

![Issue High](https://user-images.githubusercontent.com/5249806/77861122-dbe60a80-725e-11ea-961a-a79ae569c614.jpg)
384 High

If you travel further up, one of the LODs begins to show. At the starting elevation it is very faint.

![Xcode Good](https://user-images.githubusercontent.com/5249806/77861314-dccb6c00-725f-11ea-9a5a-eb70629fdfde.jpg)
![Xcode Bad](https://user-images.githubusercontent.com/5249806/77861315-dfc65c80-725f-11ea-8fc1-104d4bbfa894.jpg)

Both of these screenshots were taken in the same GPU frame capture. I am not sure what to make of it. For most of the capture everything seems fine, but for a small part in the last stage of the frame it is broken, but it looks like it is fine at the end of the frame. I'm not sure if this is Xcode messing with the results since it plays back the frame in a mirror or not.

**Comment by huwb** [comment]
Just out of interest, does #464 being merged in affect this? I guess its unlikely but i dont trust much when there are NaNs around..

**Comment by daleeidd** [comment]
No changes to this one. Still an issue.

**Comment by daleeidd** [comment]
![DebugGUI iGPU Issue](https://user-images.githubusercontent.com/5249806/79101980-23b37880-7dad-11ea-9b80-dbc3aa6c624b.jpg)

This is what I am getting for URP standalone builds on MacOS iGPU. Works fine with URP/eGPU and works fine BIRP/iGPU. Doesn't affect the editor and it isn't affected by LOD resolution.

**Comment by daleeidd** [comment]
I briefly had an M1 Mac which didn't exhibit this issue. I think we can wait this one out and close it once Apple converts their lineup to their M series chips.

**Comment by huwb** [comment]
Sounds great to me. Is that a thing that will happen soon? Feel free to close when you deem it appropriate.

**Comment by daleeidd** [comment]
Within two years. I'll close this and mark it as *won't fix*. If anyone has this issue and needs it fixed then please comment and we will reopen.
