### ISSUE TITLE
Broken Underwater Effects When Using Rotated Camera

### ISSUE THREAD

**Issue by generalsofttr** [wave-harmonic/crest#492]
When the camera is rotated 90 degrees (around z axis) , underwater effects are broken.   (tried to reposition the UnderWaterCurtainGeom and UnderWaterMeniscus objects accordingly, but no result)

Is there any quick fix to this problem ?

Crest version : 10.0 , Unity version : 2019.2.6f1

(Below is a screenshot from the official demo screen, only the camera is rotated )

![crest_underwater_90degree](https://user-images.githubusercontent.com/60553205/80609308-9a54a500-8a40-11ea-83dd-5c220b27bff8.PNG)

**Comment by moosichu** [comment]
Hi, due to the way underwater works in BIRP (using a piece of geometry called a skirt) this is a difficult problem to solve. As we are trying to move over to a post-processing based solution (see #299) where this just works out-of-the-box, we unlikely to fix this in a deprecated solution. Give that branch a try and let us know if it works for you.

**Comment by daleeidd** [comment]
The new underwater effect which solves this problem will be out in 4.12.

**Comment by daleeidd** [comment]
4.12 is out with the new underwater implementation which solves this problem.
