### ISSUE TITLE
"Write transparent motion vectors" material toggle

### ISSUE THREAD

**Issue by olavrv** [wave-harmonic/crest#564]
In the regular HDRP lit material, when transparent - there is a toggle mode to enable "Write transparent motion vectors". It is essential to have the same feature in the Crest HDRP ocean material, so that it is possible to get motion vectors for Temporal Anti Aliasing (TAA) on the ocean surface.

**Comment by olavrv** [comment]
Any progress on this?

**Comment by daleeidd** [comment]
I had a look and the shader graph we use doesn't provide this feature so we would have to add a motion vector pass by hand. It appears possible but maintaining it is a concern. I'll report back here with a more concrete answer after talking with the others.

**Comment by olavrv** [comment]
@daleeidd Thank you very much!

**Comment by huwb** [comment]
The new shadergraph setup in 2020.1 looks like it paves the way for this. It allows a single shadergraph to tackle multiple render pipelines, and seems to have per-pipeline master node settings.

From the hdrp documentation:

> To compute motion vectors for a GameObject, HDRP uses the difference between the GameObject’s position in the current and previous frame.

I would guess that for TAA to work properly it need really-correct MVs, that capture the motion/deformation of the surface. I'm guessing to do this well we'd need to write our own custom MVs.

An issue for this is that we don't automatically have the velocities. i tried in the past to store off previous state of the water, which could then be used to compute velocity, but this opened a can of worms (it required storing not just the previous cascade data, but the entire ocean state such as position, scale, etc so that data from the previous frame could be looked up and used correctly).

I think maybe the best path is adding a gerstner velocities data that is perhaps populated at the same time as the gerstner shape. This would give velocities that could then be used for TAA hopefully, and would also be usable for seeding VFX data which also want velocities for particle emissions.

**Comment by olavrv** [comment]
@huwb Fantastic news!

The ideal is full motion vectors on wave motion (vertices?) and camera/object. But a nice start would be to get object/camera motion vectors - I don't know if this is possible on it's own, or if it is a low hanging fruit

**Comment by olavrv** [comment]
With latest HDRP feature ocean-sg branch, there are still no motion vectors for ocean. Try window\analysis\renderer debugger and view motion vectors to see. FYI.

Important to get this fixed, since both TAA and DLSS uses motion vectors, and these are the most common AA techniques used atm.

**Comment by huwb** [comment]
I've put my notes from my last round of investigations onto the public wiki in case others can chip in. I think the next steps are to look into rendering MVs ourselves using a render hook (i guess looking at hdrp first), or finding a workaround for the object MVs being funky. i'm not sure what the workaround would look like right now, so hooking into the MV pass is probably the best path forward, if that is possible.

https://github.com/wave-harmonic/crest/wiki/Motion-Vectors

**Comment by huwb** [comment]
I've managed to get it partly working but still needs more work.

In case it helps, AMD FidelityFX works across all platforms (it claims) and does not require motion vectors (it claims). https://forum.unity.com/threads/amd-fidelityfx-super-resolution-fsr-preview-now-available.1141495/

Obv motion vectors are good for more than just DLSS and we still want to support MVs, so leaving this open and will report back if I can make progress.

**Comment by daleeidd** [comment]
This was released with 4.14 and working 100% with 4.15 (toggle wasn't always working in 4.14) so I will be closing. Thank you for reporting.
