### ISSUE TITLE
Toggleable automatic ocean clipping under Terrain with DepthCache

### ISSUE THREAD

**Issue by StarChick971** [wave-harmonic/crest#567]
I managed to get the first _seafloor depth slice_ as texture2d but it is not the full texture from OceanDepthCache, i displayed it on a quad in my scene:
![image](https://media.discordapp.net/attachments/559872309947793409/709531519034851348/unknown.png)

Now I can use this texture as input for clip surface shader to remove water under the terrain (in case your terrain or scene goes below sea level).
**Would it be possible to simply add such feature as a new depth-clip shader?**
The idea is to clip water under any meshfiltered by layer (i.e terrain) registering into the depth cache:
- without clipping
![image](https://media.discordapp.net/attachments/559872309947793409/709534803090735255/unknown.png)
- while clipping
![image](https://media.discordapp.net/attachments/559872309947793409/709534947601416293/unknown.png)

I would advise to pre-bake the ocean depth in editor to clip the ocean surface with the filtered layers.

**Comment by daleeidd** [comment]
I tried this idea myself a while ago. I was just using the ocean depth value directly in the shader. It only worked for me well when the _Attenuation In Shallows_ value on _SimSettingsAnimatedWaves_ is set to 1. Otherwise, water will rise at the shoreline and be clipped above the terrain. But with enough padding it might work.

**Comment by StarChick971** [comment]
> I tried this idea myself a while ago. I was just using the ocean depth value directly in the shader. It only worked for me well when the _Attenuation In Shallows_ value on _SimSettingsAnimatedWaves_ is set to 1. Otherwise, water will rise at the shoreline and be clipped above the terrain. But with enough padding it might work.

Yes I know, especially in stormy conditions waves are just cut brutally when reaching the clip surface above the terrain.
It might need to clip only vertices below terrain to fix that behaviour, thus we could even have shorelines wave that way like this:
![image](http://i359.photobucket.com/albums/oo33/N_A_I_M_A/shoreanimation_zpsyeunk4vj.gif~original)

**Comment by huwb** [comment]
Hello all,

It's not clear to me that clipping under terrain helps. Is this intended to help performance?

The gpu depth test will fail if the water is behind terrain, so any surface under the terrain will not even begin drawing.

**Comment by StarChick971** [comment]
> Hello all,
> 
> It's not clear to me that clipping under terrain helps. Is this intended to help performance?
> 
> The gpu depth test will fail if the water is behind terrain, so any surface under the terrain will not even begin drawing.

No, it isn't about performance as we already talk about very few improvement concerning it on Discord. The topic here is to clip automatically the surface below terrain without the need to create a clipping texture with quads ourselves to remove water locally. Just imagine a volcano island, you simply don't want water to be visible inside like in this course: [MR Sharing 250: HoloLens and immersive headset](https://docs.microsoft.com/en-us/windows/mixed-reality/mixed-reality-250) (I tried this course at work both AR & VR for demonstration purposes).
The problem is I have to update the clip texture each time I modify the terrain. It is ok when working alone on the same scene but not within team (one dev in charge of land terrain, other for water related stuff, etc.)

**Comment by huwb** [comment]
Ahh ok.

Some times it's enough to just slap in a quad to give the rough shape of the hole is it's a simple shape.

Another thing we've added is a WaterBody script which defines where water should be located. There are some words about it in the user guide here on GitHub (not in urp/hdrp until next release).

But to actually answer the question, yeah I guess this could be added. Could clip if depth is less than -2m or something like that to avoid clipping being visible. I think this could just be an option directly on the ocean material, rather than needing the clipping system active. I could try this in a bit.

**Comment by huwb** [comment]
Seemed to work, and does not require the clipping surface (*Create Clip Surface Data* toggle on ocean component), so is more efficient as well.

https://github.com/crest-ocean/crest/pull/582

Feedback welcome

**Comment by daleeidd** [comment]
Released in 4.5. HDRP missed this feature but will add it.
