### ISSUE TITLE
Static lighting sky and foam bubbles create weird square shapes

### ISSUE THREAD

**Issue by CheoCD** [wave-harmonic/crest#671]
Hello, I'm currently using Crest HDRP in an empty project on Unity 2020.1.8f1 with HDRP 8.2.0. The following issue happens in both the editor and a build, and I'm using Windows and a GTX 1070.

When a static lighting sky is set through an environment profile in the lighting panel, square shapes are created in the ocean as shown by the images below. The strength and color of those shapes are determined by the "Foam bubbles coverage" and "Foam bubbles colour" values in the default "Ocean" and "Ocean-Underwater" materials - setting the foam bubbles coverage value to 0 or the color to black removes the shapes.

![Crest1](https://user-images.githubusercontent.com/50143630/96592564-d29ab900-12e8-11eb-8f1d-67ca9675614b.png)
![Crest2](https://user-images.githubusercontent.com/50143630/96592580-d75f6d00-12e8-11eb-8ac9-61aefd94217e.png)
![Crest3](https://user-images.githubusercontent.com/50143630/96592586-d8909a00-12e8-11eb-8abf-dafff373e455.png)

I hope this bug report will be useful and that you will be able to solve this issue :)

**Comment by daleeidd** [comment]
Thank you for reporting.

I have removed HDRP since it is an issue for all pipelines.

The issue is that foam bubbles requires a higher mesh density (mesh density is affected by the detail params _Lod Data Resolution_ and _Geometry Down Sampling Factor_) to look good at that distance. This shouldn't be the case as we want visual quality to be consistent. This can also happen when close to the surface if the mesh density is low enough.

We will have to investigate further. But for now I recommend scripting the foam bubble coverage (might have a different name for HDRP) so that no foam bubbles are shown when the camera is at that height.

**Comment by huwb** [comment]
It might help to tweak the foam bubble texture scale - the texture itself should ideally help break up the regularity of the mesh triangles.

**Comment by daleeidd** [comment]
Fix will be out for 4.13

**Comment by daleeidd** [comment]
4.13 has been release. Thank you for reporting.
