### ISSUE TITLE
[URP] Bug on underwater effect - flickering with Enviro asset. Missing camera type check.

### ISSUE THREAD

**Issue by Magic73** [wave-harmonic/crest#714]
If there are other types of cameras in the scene besides the game camera, then these are also used in the various callbacks. In the underwater effect this generates a flicker

Instead only a Game camera should be used.

I discovered this issue using Enviro asset. This asset draw into an hidden camera used for rendering reflection probes.
When I went underwater, the screen starts to flicker due to a massive redraw calls.

**Versions**
I tested with URP version.

**To Reproduce**
Install Enviro, and then go underwater.

**Platform**
Any

**Additional context**
Solution:
Edit the UnderwaterEffect.cs and change the BeginCameraRendering method, adding the camera type check:

        private void BeginCameraRendering(ScriptableRenderContext scriptableRenderContext, Camera camera)
        {
            if (camera.cameraType != CameraType.Game) return;

            _currentCamera = camera;
        }

I think that this check should be done in the other places where you use this callback:

**RenderPipelineManager.beginCameraRendering**

I also added this:

            if (camera.cameraType != CameraType.Game) return;

at the beginning of each 

      public void BeginCameraRendering(ScriptableRenderContext context, Camera camera)

inside these files:
UnderwaterEffect.cs (obviously)
OceanDepthCache.cs
OceanChunkRenderer.cs
OceanPlanarReflection.cs

These are the available camera types:

    //     Describes different types of camera.
    [Flags]
    public enum CameraType
    {
        //     Used to indicate a regular in-game camera.
        Game = 1,
        //     Used to indicate that a camera is used for rendering the Scene View in the Editor.
        SceneView = 2,
        //     Used to indicate a camera that is used for rendering previews in the Editor.
        Preview = 4,
        //     Used to indicate that a camera is used for rendering VR (in edit mode) in the
        //     Editor.
        VR = 8,
        //     Used to indicate a camera that is used for rendering reflection probes.
        Reflection = 16
    }

**Comment by Magic73** [comment]
Inside the OceanDeepCache, the check should be:

 if (camera.cameraType != CameraType.Game && camera.cameraType != CameraType.SceneView && camera.cameraType != CameraType.Preview) return;

**Comment by daleeidd** [comment]
Thank you for finding the problem. I don't think that will fully address the problem for the depth camera though. I think something like `camera != _camDepthCache` would cover all cases as it will limit the function to the created camera. But that will require more changes for it to work. I'll look into this more.

**Comment by Magic73** [comment]
No, this is related to the depth camera, just with the integration with other asset.
In this case with Enviro, which use its own reflection probe, and it update every frame, so that each BeginCameraRendering is called even with camera != Game type.

Instead, the check into OceanDeepCache should include the other camera types, because the DeepCache could be update inside the editor too, so that camera type should be included also.

**Comment by daleeidd** [comment]
Thanks. I had a look over all of them and fixed the ones that needed fixing. Fix will be out for 4.8. Details below:

**UnderwaterEffect.cs**
Removed *BeginCameraRendering*. This one didn't make much sense since we expect the parent GO to have a camera so we will use that instead. This may have been an issue since that event sets the camera for *_CameraForward*, which is set in *LateUpdate*, resulting in the wrong camera forward being used.

**OceanDepthCache.cs**
Removed *BeginCameraRendering*. This one could execute other cameras, but it never ran every frame so could have been missed.

**OceanPlanarReflection.cs**
Uses `if (camera != _camViewpoint)`already  so it will only render for the camera attached to same game object. No change required.

**OceanChunkRenderer.cs**
The usage for this one is correct. *BeginCameraRendering* sets the camera property to solve *Camera.current* not being supported. *OnWillRenderObject* is called right after *BeginCameraRendering* for the camera so the correct camera is set.

**Comment by daleeidd** [comment]
@Magic73 4.8 is out. Please let me know if it solves the issues for you when you have a chance. Thank you.

**Comment by daleeidd** [comment]
Closing this one. I'll reopen if we get reports of the issue persisting.
